metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

#name: ""
metricbeat.autodiscover:
    providers:
    - type: docker
      hints.enabled: true

processors:
  - drop_fields.fields: ['agent','cloud','ecs']
  - add_fields:
      target: env
      fields:
        tag: prod

setup.kibana.host: "http://kibana:5601"
setup.kibana.username: user 
setup.kibana.password: PASS
#setup.dashboards.enabled: true
setup.ilm.enabled: false
setup.ilm.check_exists: false



output.elasticsearch:
  hosts: 'https://elastic:9200'
  username: user
  password: PASS
  ssl.verification_mode: "none"
